version: '3.9'

services:
  packagespostgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: PackageDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5442:5442"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: