version: '3.9'

services:
  packagespostgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: PackageDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5442:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
 

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql



  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "1242:80"
    depends_on:
      - packagespostgres

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
 

  packagesapi:
    build:
      context: .
      dockerfile: src/Services/Packages/PackagesService.API/Dockerfile
    depends_on:
      - packagespostgres
    ports:
      - "7777:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  deliveryapi:
    build:
      context: .
      dockerfile: src/Services/Delivery/DeliveryService.API/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "1111:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

volumes:
  pgdata:
  sqlserverdata:  