version: '3.9'

services:
  packagespostgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: PackageDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5442:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data



  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "1242:80"
    depends_on:
      - packagespostgres
 

  packagesapi:
    build:
      context: .
      dockerfile: src/Services/Packages/PackagesService.API/Dockerfile
    depends_on:
      - packagespostgres
    ports:
      - "7777:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

volumes:
  pgdata: