name: CI Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./PackagesTask.sln

      - name: Build solution
        run: dotnet build ./PackagesTask.sln --configuration Release --no-restore

      - name: Run Unit Tests for AuthService
        run: dotnet test ./tests/Services/Auth/AuthService.Tests/AuthService.Tests.csproj --configuration Release --no-build

      - name: Run Unit Tests for DeliveryService
        run: dotnet test ./tests/Services/Delivery/DeliveryService.Tests/DeliveryService.Tests.csproj --configuration Release --no-build

      - name: Run Unit Tests for PackagesService
        run: dotnet test ./tests/Services/Packages/PackagesService.Tests/PackagesService.Tests.csproj --configuration Release --no-build

      # Optional: Docker image build (can add push later)
      - name: Build Docker Images
        run: docker compose -f docker-compose.yml build