name: CI & Push to GHCR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


permissions:
  contents: read
  packages: write 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./PackagesTask.sln

      - name: Build solution
        run: dotnet build ./PackagesTask.sln --configuration Release --no-restore

      - name: Run Unit Tests for AuthService
        run: dotnet test ./tests/Services/Auth/AuthService.Tests/AuthService.Tests.csproj --configuration Release --no-build

      - name: Run Unit Tests for DeliveryService
        run: dotnet test ./tests/Services/Delivery/DeliveryService.Tests/DeliveryService.Tests.csproj --configuration Release --no-build

      - name: Run Unit Tests for PackagesService
        run: dotnet test ./tests/Services/Packages/PackagesService.Tests/PackagesService.Tests.csproj --configuration Release --no-build


      # -----------------------------
      # PUSH TO GHCR
      # -----------------------------
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Yarp API Gateway
        run: |
           docker build \
              -t ghcr.io/${{ github.repository_owner }}/yarp-gateway:latest \
              -f src/APIsGateway/YarpAPIsGateway/Dockerfile \
              .  # context is the root
            docker push ghcr.io/${{ github.repository_owner }}/yarp-gateway:latest

      - name: Build and Push AuthService
        run: |
           docker build \
              -t ghcr.io/${{ github.repository_owner }}/auth-service:latest \
              -f src/Services/Authorization/AuthService/Dockerfile \
              .  # context is the root
            docker push ghcr.io/${{ github.repository_owner }}/auth-service:latest

      - name: Build and Push DeliveryService
        run: |
           docker build \
              -t ghcr.io/${{ github.repository_owner }}/delivery-service:latest \
              -f src/Services/Delivery/DeliveryService.API/Dockerfile \
              .  # context is the root
            docker push ghcr.io/${{ github.repository_owner }}/delivery-service:latest

      - name: Build and Push PackagesService
        run: |
           docker build \
              -t ghcr.io/${{ github.repository_owner }}/packages-service:latest \
              -f src/Services/Packages/PackagesService.API/Dockerfile \
              .  # context is the root
            docker push ghcr.io/${{ github.repository_owner }}/packages-service:latest

